services:
  - name: ai-asst-doctor-backend
    type: web
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: API_KEY
        sync: false  # Set this manually in Render dashboard
